class EnvironmentVariables:
    LEETBOT_IS_LOCAL_DEPLOYMENT: str = "LEETBOT_IS_LOCAL_DEPLOYMENT" 
    LEETBOT_JSON_PATH: str = "LEETBOT_JSON_PATH"
    LEETBOT_S3_BUCKET_NAME: str = "LEETBOT_S3_BUCKET_NAME"
    LEETBOT_SLACK_TOKEN: str = "LEETBOT_SLACK_TOKEN"
