class CS61B: 
    id                      = "id"
    reading                 = "reading"
    lecture_title           = "lecture_title"
    lecture_video           = "lecture_video"
    lecture_slides          = "lecture_slides"
    lecture_guide           = "lecture_guide"
    discussion_worksheet    = "discussion_worksheet"
    discussion_slides       = "discussion_slides"
    discussion_video        = "discussion_video"
    discussion_solution     = "discussion_solution"
    lab                     = "lab"
